-- ============================================================
-- 蒋的APP - Supabase 数据库迁移脚本 V3.0
-- 执行方式: Supabase Dashboard → SQL Editor → 粘贴执行
-- ============================================================

-- 1. User 表（用户表，增加 gacha_remaining 字段）
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  avatar TEXT NOT NULL DEFAULT '😀',
  gacha_remaining INTEGER NOT NULL DEFAULT 3,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 如果已有 users 表，添加 gacha_remaining 列
DO 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'users' AND column_name = 'gacha_remaining'
  ) THEN
    ALTER TABLE users ADD COLUMN gacha_remaining INTEGER NOT NULL DEFAULT 3;
  END IF;
END
;

-- User RLS 策略
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "任何人可查看用户列表"
  ON users FOR SELECT USING (true);

CREATE POLICY "任何人可注册用户"
  ON users FOR INSERT WITH CHECK (true);

CREATE POLICY "用户可更新自己的资料"
  ON users FOR UPDATE USING (true);

-- 2. Friend 表（好友关系）
CREATE TABLE IF NOT EXISTS friends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  friend_id TEXT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, friend_id)
);
ALTER TABLE friends ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
UPDATE friends SET created_at = now() WHERE created_at IS NULL;

DELETE FROM friends a
USING friends b
WHERE a.ctid < b.ctid
  AND a.user_id = b.user_id
  AND a.friend_id = b.friend_id;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.friends'::regclass
      AND conname = 'friends_user_id_friend_id_key'
  ) THEN
    ALTER TABLE friends
      ADD CONSTRAINT friends_user_id_friend_id_key UNIQUE (user_id, friend_id);
  END IF;
END $$;

INSERT INTO friends (user_id, friend_id)
SELECT f.friend_id, f.user_id
FROM friends f
WHERE f.user_id IS NOT NULL
  AND f.friend_id IS NOT NULL
  AND f.user_id <> f.friend_id
ON CONFLICT (user_id, friend_id) DO NOTHING;

-- Friend RLS 策略
ALTER TABLE friends ENABLE ROW LEVEL SECURITY;

CREATE POLICY "任何人可查询好友关系"
  ON friends FOR SELECT USING (true);

CREATE POLICY "任何人可添加好友"
  ON friends FOR INSERT WITH CHECK (true);

CREATE POLICY "任何人可删除好友"
  ON friends FOR DELETE USING (true);

-- 3. Card 表（卡牌收藏）
CREATE TABLE IF NOT EXISTS cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  owner_id TEXT NOT NULL REFERENCES users(id),
  name TEXT NOT NULL,
  rarity TEXT NOT NULL CHECK (rarity IN ('N','R','SR','SSR','UR')),
  image TEXT DEFAULT NULL,
  trade_id TEXT UNIQUE,
  trade_count INTEGER NOT NULL DEFAULT 0,
  is_favorited BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- V2 卡牌资产字段：owner_id 作为资产归属，trade_id 用于交易，is_favorited 用于收藏
ALTER TABLE cards ADD COLUMN IF NOT EXISTS owner_id TEXT REFERENCES users(id);
ALTER TABLE cards ADD COLUMN IF NOT EXISTS trade_id TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS trade_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS is_favorited BOOLEAN NOT NULL DEFAULT false;
UPDATE cards SET owner_id = user_id WHERE owner_id IS NULL;
ALTER TABLE cards ALTER COLUMN owner_id SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS cards_trade_id_unique ON cards(trade_id) WHERE trade_id IS NOT NULL;

-- Card RLS 策略
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "任何人可查询卡牌"
  ON cards FOR SELECT USING (true);

CREATE POLICY "任何人可添加卡牌"
  ON cards FOR INSERT WITH CHECK (true);

CREATE POLICY "任何人可更新卡牌"
  ON cards FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "用户可删除自己的卡牌"
  ON cards FOR DELETE USING (true);

-- 4. Trades 表（卡牌交易码）
CREATE TABLE IF NOT EXISTS trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id BIGINT NOT NULL REFERENCES cards(id),
  from_user TEXT NOT NULL REFERENCES users(id),
  to_user TEXT REFERENCES users(id),
  trade_code TEXT NOT NULL UNIQUE,
  used BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE trades ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "trade_select_all" ON trades;
DROP POLICY IF EXISTS "trade_insert_all" ON trades;
DROP POLICY IF EXISTS "trade_update_all" ON trades;

CREATE POLICY "trade_select_all" ON trades FOR SELECT USING (true);
CREATE POLICY "trade_insert_all" ON trades FOR INSERT WITH CHECK (true);
CREATE POLICY "trade_update_all" ON trades FOR UPDATE USING (true) WITH CHECK (true);

-- 5. Gacha Limits 表（抽卡次数记录，按用户+日期隔离）
CREATE TABLE IF NOT EXISTS gacha_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  date_key TEXT NOT NULL,
  used_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, date_key)
);

-- Gacha Limits RLS 策略
ALTER TABLE gacha_limits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "任何人可查询抽卡次数"
  ON gacha_limits FOR SELECT USING (true);

CREATE POLICY "任何人可插入抽卡次数"
  ON gacha_limits FOR INSERT WITH CHECK (true);

CREATE POLICY "任何人可更新抽卡次数"
  ON gacha_limits FOR UPDATE USING (true);

-- 6. Messages 表（全局留言板，所有设备同步显示）
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id TEXT,
  user_id TEXT REFERENCES users(id),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE messages ADD COLUMN IF NOT EXISTS client_id TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS user_id TEXT REFERENCES users(id);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
UPDATE messages SET content = '' WHERE content IS NULL;
UPDATE messages SET created_at = now() WHERE created_at IS NULL;
ALTER TABLE messages ALTER COLUMN content SET NOT NULL;
ALTER TABLE messages ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE messages ALTER COLUMN created_at SET DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS messages_client_id_unique
  ON messages(client_id)
  WHERE client_id IS NOT NULL;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'messages'
      AND column_name = 'type'
  ) THEN
    ALTER TABLE messages ALTER COLUMN type DROP NOT NULL;
  END IF;
END $$;

-- Messages RLS 策略
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "任何人可查询留言" ON messages;
DROP POLICY IF EXISTS "任何人可发送留言" ON messages;
DROP POLICY IF EXISTS "用户可删除自己的留言" ON messages;
DROP POLICY IF EXISTS "任何人可删除留言" ON messages;

CREATE POLICY "任何人可查询留言"
  ON messages FOR SELECT USING (true);

CREATE POLICY "任何人可发送留言"
  ON messages FOR INSERT WITH CHECK (true);

CREATE POLICY "任何人可删除留言"
  ON messages FOR DELETE USING (true);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
    AND NOT EXISTS (
      SELECT 1
      FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'messages'
    ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE messages;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
    AND NOT EXISTS (
      SELECT 1
      FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'friends'
    ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE friends;
  END IF;
END $$;

-- ============================================================
-- 验证：查看表结构
-- ============================================================
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('users', 'friends', 'cards', 'gacha_limits')
ORDER BY table_name;
