-- Repeatable Supabase fix script for users, cards, trades, friends, and messages.

ALTER TABLE users ADD COLUMN IF NOT EXISTS gacha_remaining INTEGER NOT NULL DEFAULT 3;

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "users_select_all" ON users;
DROP POLICY IF EXISTS "users_insert_all" ON users;
DROP POLICY IF EXISTS "users_update_all" ON users;
CREATE POLICY "users_select_all" ON users FOR SELECT USING (true);
CREATE POLICY "users_insert_all" ON users FOR INSERT WITH CHECK (true);
CREATE POLICY "users_update_all" ON users FOR UPDATE USING (true) WITH CHECK (true);

ALTER TABLE cards ADD COLUMN IF NOT EXISTS owner_id TEXT REFERENCES users(id);
ALTER TABLE cards ADD COLUMN IF NOT EXISTS trade_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS trade_id TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS is_favorited BOOLEAN NOT NULL DEFAULT false;
UPDATE cards SET owner_id = user_id WHERE owner_id IS NULL;
ALTER TABLE cards ALTER COLUMN owner_id SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS cards_trade_id_unique ON cards(trade_id) WHERE trade_id IS NOT NULL;

ALTER TABLE cards ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cards_select_all" ON cards;
DROP POLICY IF EXISTS "cards_insert_all" ON cards;
DROP POLICY IF EXISTS "cards_update_all" ON cards;
DROP POLICY IF EXISTS "cards_delete_all" ON cards;
CREATE POLICY "cards_select_all" ON cards FOR SELECT USING (true);
CREATE POLICY "cards_insert_all" ON cards FOR INSERT WITH CHECK (true);
CREATE POLICY "cards_update_all" ON cards FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "cards_delete_all" ON cards FOR DELETE USING (true);

CREATE TABLE IF NOT EXISTS trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id BIGINT NOT NULL REFERENCES cards(id),
  from_user TEXT NOT NULL REFERENCES users(id),
  to_user TEXT REFERENCES users(id),
  trade_code TEXT NOT NULL UNIQUE,
  used BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE trades ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "trade_select_all" ON trades;
DROP POLICY IF EXISTS "trade_insert_all" ON trades;
DROP POLICY IF EXISTS "trade_update_all" ON trades;
CREATE POLICY "trade_select_all" ON trades FOR SELECT USING (true);
CREATE POLICY "trade_insert_all" ON trades FOR INSERT WITH CHECK (true);
CREATE POLICY "trade_update_all" ON trades FOR UPDATE USING (true) WITH CHECK (true);

ALTER TABLE friends ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "friends_select_all" ON friends;
DROP POLICY IF EXISTS "friends_insert_all" ON friends;
DROP POLICY IF EXISTS "friends_delete_all" ON friends;
CREATE POLICY "friends_select_all" ON friends FOR SELECT USING (true);
CREATE POLICY "friends_insert_all" ON friends FOR INSERT WITH CHECK (true);
CREATE POLICY "friends_delete_all" ON friends FOR DELETE USING (true);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id TEXT,
  user_id TEXT REFERENCES users(id),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE messages ADD COLUMN IF NOT EXISTS client_id TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS user_id TEXT REFERENCES users(id);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();
UPDATE messages SET content = '' WHERE content IS NULL;
UPDATE messages SET created_at = now() WHERE created_at IS NULL;
ALTER TABLE messages ALTER COLUMN content SET NOT NULL;
ALTER TABLE messages ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE messages ALTER COLUMN created_at SET DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS messages_client_id_unique
  ON messages(client_id)
  WHERE client_id IS NOT NULL;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'messages'
      AND column_name = 'type'
  ) THEN
    ALTER TABLE messages ALTER COLUMN type DROP NOT NULL;
  END IF;
END $$;

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "messages_select_all" ON messages;
DROP POLICY IF EXISTS "messages_insert_all" ON messages;
DROP POLICY IF EXISTS "messages_delete_all" ON messages;
CREATE POLICY "messages_select_all" ON messages FOR SELECT USING (true);
CREATE POLICY "messages_insert_all" ON messages FOR INSERT WITH CHECK (true);
CREATE POLICY "messages_delete_all" ON messages FOR DELETE USING (true);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
    AND NOT EXISTS (
      SELECT 1
      FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'messages'
    ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE messages;
  END IF;
END $$;
