-- ============================================================
-- 蒋的APP - Supabase 数据库迁移脚本 V3.0
-- 执行方式: Supabase Dashboard → SQL Editor → 粘贴执行
-- ============================================================

-- 1. User 表（用户表，增加 gacha_remaining 字段）
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  avatar TEXT NOT NULL DEFAULT '😀',
  gacha_remaining INTEGER NOT NULL DEFAULT 3,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 如果已有 users 表，添加 gacha_remaining 列
DO 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'users' AND column_name = 'gacha_remaining'
  ) THEN
    ALTER TABLE users ADD COLUMN gacha_remaining INTEGER NOT NULL DEFAULT 3;
  END IF;
END
;

-- User RLS 策略
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "任何人可查看用户列表"
  ON users FOR SELECT USING (true);

CREATE POLICY "任何人可注册用户"
  ON users FOR INSERT WITH CHECK (true);

CREATE POLICY "用户可更新自己的资料"
  ON users FOR UPDATE USING (true);

-- 2. Friend 表（好友关系）
CREATE TABLE IF NOT EXISTS friends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  friend_id TEXT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, friend_id)
);

-- Friend RLS 策略
ALTER TABLE friends ENABLE ROW LEVEL SECURITY;

CREATE POLICY "任何人可查询好友关系"
  ON friends FOR SELECT USING (true);

CREATE POLICY "任何人可添加好友"
  ON friends FOR INSERT WITH CHECK (true);

CREATE POLICY "任何人可删除好友"
  ON friends FOR DELETE USING (true);

-- 3. Card 表（卡牌收藏）
CREATE TABLE IF NOT EXISTS cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  owner_id TEXT NOT NULL REFERENCES users(id),
  name TEXT NOT NULL,
  rarity TEXT NOT NULL CHECK (rarity IN ('N','R','SR','SSR','UR')),
  image TEXT DEFAULT NULL,
  trade_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- V2 卡牌资产字段：owner_id 作为资产归属，trade_count 记录交易次数
ALTER TABLE cards ADD COLUMN IF NOT EXISTS owner_id TEXT REFERENCES users(id);
ALTER TABLE cards ADD COLUMN IF NOT EXISTS trade_count INTEGER NOT NULL DEFAULT 0;
UPDATE cards SET owner_id = user_id WHERE owner_id IS NULL;
ALTER TABLE cards ALTER COLUMN owner_id SET NOT NULL;

-- Card RLS 策略
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "任何人可查询卡牌"
  ON cards FOR SELECT USING (true);

CREATE POLICY "任何人可添加卡牌"
  ON cards FOR INSERT WITH CHECK (true);

CREATE POLICY "任何人可更新卡牌"
  ON cards FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "用户可删除自己的卡牌"
  ON cards FOR DELETE USING (true);

-- 4. Trades 表（卡牌交易码）
CREATE TABLE IF NOT EXISTS trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id BIGINT NOT NULL REFERENCES cards(id),
  from_user TEXT NOT NULL REFERENCES users(id),
  to_user TEXT REFERENCES users(id),
  trade_code TEXT NOT NULL UNIQUE,
  used BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE trades ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "trade_select_all" ON trades;
DROP POLICY IF EXISTS "trade_insert_all" ON trades;
DROP POLICY IF EXISTS "trade_update_all" ON trades;

CREATE POLICY "trade_select_all" ON trades FOR SELECT USING (true);
CREATE POLICY "trade_insert_all" ON trades FOR INSERT WITH CHECK (true);
CREATE POLICY "trade_update_all" ON trades FOR UPDATE USING (true) WITH CHECK (true);

-- 5. Gacha Limits 表（抽卡次数记录，按用户+日期隔离）
CREATE TABLE IF NOT EXISTS gacha_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  date_key TEXT NOT NULL,
  used_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, date_key)
);

-- Gacha Limits RLS 策略
ALTER TABLE gacha_limits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "任何人可查询抽卡次数"
  ON gacha_limits FOR SELECT USING (true);

CREATE POLICY "任何人可插入抽卡次数"
  ON gacha_limits FOR INSERT WITH CHECK (true);

CREATE POLICY "任何人可更新抽卡次数"
  ON gacha_limits FOR UPDATE USING (true);

-- 5. Messages 表（留言板，增加 user_id 隔离）
-- 如果旧表已存在且无 user_id 列，则添加
DO 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'messages' AND column_name = 'user_id'
  ) THEN
    ALTER TABLE messages ADD COLUMN user_id TEXT REFERENCES users(id);
  END IF;
END
;

-- 为新记录设置默认 user_id（已有历史消息标记为匿名）
UPDATE messages SET user_id = NULL WHERE user_id IS NULL;

-- Messages RLS 策略
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "任何人可查询留言"
  ON messages FOR SELECT USING (true);

CREATE POLICY "任何人可发送留言"
  ON messages FOR INSERT WITH CHECK (true);

CREATE POLICY "用户可删除自己的留言"
  ON messages FOR DELETE USING (user_id = auth.uid()::TEXT OR user_id IS NULL);

-- ============================================================
-- 验证：查看表结构
-- ============================================================
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('users', 'friends', 'cards', 'gacha_limits')
ORDER BY table_name;
